baseurl = "https://donaldfountain.ai"
languageCode = "en-us"
title = "AI Governance Practitioner Who Builds Things"

# Theme i18n support
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
hasCJKLanguage = false

# Google Analytics
googleAnalytics = "G-WVR1680KCZ"

[pagination]
pagerSize = 3