# Configure main menu and social menu

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/vintagedon"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "X"
url = "https://x.com/donaldfountain"

[social.params]
icon = "brand-twitter"